### ISSUE TITLE
Nova Patch

### ISSUE THREAD

**Issue by smalleni** [cybertron/openstack-virtual-baremetal#17]
Does the nova patch hold good for liberty as well? Thanks.

**Comment by steveb** [comment]
I'll refresh the patch for liberty and mitaka

**Comment by smalleni** [comment]
@steveb thanks!

**Comment by cybertron** [comment]
I just tried the patch on master Nova and it still applied cleanly.  Maybe we should drop the version directory?

**Comment by cybertron** [comment]
I've pushed b4a44e47d3801ff7bd7b8ce51709a36650227762 which removes the version-specifier from the patch path. To my knowledge the patch applies cleanly to every version since Kilo, and if it does merge conflict at some point we can split the patches into version directories again.
