### ISSUE TITLE
Readme needs to be updated

### ISSUE THREAD

**Issue by smalleni** [cybertron/openstack-virtual-baremetal#20]
When talking abt nova patches, neutron changes etc. the readme refers to the "host cloud"  but it is not clear whether those changes should be on the controllers,computes or undercloud? A bit more detail in the readme would greatly help.

**Comment by cybertron** [comment]
I've pushed 8009f6b68a171a1e913aae8c638b95d28a7e9a68 and c1dcb7d3937c74e2ee1f824526fd28a0297e8f63 which should clarify the docs on this.
