### ISSUE TITLE
more of a question than an issue

### ISSUE THREAD

**Issue by tickers** [cybertron/openstack-virtual-baremetal#26]
So you can take this, OVB, install it on an established Openstack, non prod, running Mitaka and then be able to provision a virtual baremetal server you can install TripleO Quickstart on? I have been through the read me a few times just want to make sure. 
Interestingly that would make it in my case
ESXI (baremetal install > Nested Openstack +1 node > Undercloud host hosting an overcloud
If you have a IRC that would also be great!

**Comment by steveb** [comment]
Thats correct, yes.

I personally have not tried OVB with tripleo-quickstart *yet* (I have my own ansible playbooks for OVB install) but it has been used at least for CI[1].

I'd like to see tripleo-quickstart + OVB to be a common development environment for tripleo, but I don't yet know how close we are to that. You can ask questions in #tripleo to stevebaker or bnemec

[1] https://github.com/openstack/tripleo-quickstart/blob/master/ci-scripts/full-deploy-ovb.sh

**Comment by tickers** [comment]
Thank You !! Will test this out as soon as I get a chance...

**Comment by rlandy** [comment]
I have tested running tripleo-quickstart on OVB stack. 
It works with both mitaka and master (newton).
