### ISSUE TITLE
1 out of 1 hunk FAILED -- saving rejects to file nova-pxe-boot.patch.rej

### ISSUE THREAD

**Issue by tickers** [cybertron/openstack-virtual-baremetal#27]
@mitaka nova]# patch -p1 < nova-pxe-boot.patch
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/nova/virt/libvirt/driver.py b/nova/virt/libvirt/driver.py
|index 6097fbf..e419df6 100644
|--- a/nova/virt/libvirt/driver.py
|+++ b/nova/virt/libvirt/driver.py
--------------------------
File to patch: nova-pxe-boot.patch
patching file nova-pxe-boot.patch
Hunk #1 FAILED at 4012.
1 out of 1 hunk FAILED -- saving rejects to file nova-pxe-boot.patch.rej

Using Mitaka, AIO plus 1 additional compute node, Neutron networking, on centos 7

Rej file
--- nova/virt/libvirt/driver.py
+++ nova/virt/libvirt/driver.py
@@ -4012,6 +4012,10 @@
             self._conf_non_lxc_uml(virt_type, guest, root_device_name, rescue,
                     instance, inst_path, image_meta, disk_info)

+        if (CONF.libvirt.virt_type in ['qemu', 'kvm'] and
+                instance.metadata.get('libvirt:pxe-first')):
+            guest.os_boot_dev = ['network'] + guest.os_boot_dev
+
         self._set_features(guest, instance.os_type, caps, virt_type)
         self._set_clock(guest, instance.os_type, image_meta, virt_type)

Anything else you need?

thanks

'Mike

**Comment by cybertron** [comment]
Whoops, apparently I screwed up the patching instructions for packaged Nova.  d5f6b2a4288e22030ddebf2893b8ec426dee6ea1 should fix that.  The new patching instructions should work correctly.

Thanks for bringing this to my attention and let me know if that doesn't fix the problem.
